### ISSUE TITLE
chưa đăng nhập, page Bài tập và thống kê over loading

### ISSUE THREAD

**Issue by hungminhle10072000** [hungminhle10072000/WebsiteHocTiengAnh#104]
![image](https://user-images.githubusercontent.com/57429082/178132093-85d78049-0739-46be-b4da-71666c2b32d9.png)
![image](https://user-images.githubusercontent.com/57429082/178132095-97043385-757b-4ef6-a761-c09796d2367b.png)

**Comment by nghiabv120100** [comment]
I fixed it in commit https://github.com/hungminhle10072000/WebsiteHocTiengAnh/pull/111/commits/5075932ea63c0fbbdd9abeaeefec5fb5a083a1e5
